spring:
  redis:
    host: ${spring.redis.host:localhost}
    port: ${spring.redis.port:6379}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  task:
    scheduling:
      enabled: false

  http:
    maxRetries: 3
    retryDelay: 1000

  processing:
    schedule-interval: 5s
    initial-delay: 1s
    enable-scheduling: false